spring :
  datasource:
    url: jdbc:postgresql://dpg-ch5car9jvhts7knnu8cg-a.oregon-postgres.render.com:5432/my1db
    username: my1db_user
    password: s99fAu8Q2x24FCGyzrZFC3UcgrPKDKTN
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql :true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/leetcode
#    username: postgres
#    password: admin
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect